Repository ni/niveristand-synchronization-custom-device, pull requests merged in 2019-06, with the labels that each got.

#31 Reorder tabs to make Time Reference the default
  Source/System Explorer/Main Page.vi
Labels: enhancement

#32 Fix PXI Chassis Clock time reference
  Source/Engine/Set Timekeeper CLK10 Input.vi
  Source/System Explorer/Main Page.vi
  Source/System Explorer/Prevent and Clear Backplane Time Ref Selection.vi
  Source/Tests/System/Linux x64 System Tests/Assets/PXI Chassis Clock.nivssdf
  Source/Tests/System/PharLap System Tests/Assets/PXI Chassis Clock.nivssdf
Labels: bug

#33 Update test config to support ATS hardware
  Source/Tests/System/Linux x64 System Tests/Assets/config.ini
  Source/Tests/System/PharLap System Tests/Assets/config.ini
  Source/Tests/System/PharLap System Tests/Assets/syncDeviceNameMismatch-config.ini
  Source/Tests/System/PharLap System Tests/test device name mismatch error.vi
Labels: tech debt
